### ISSUE TITLE
what kind of model does it support?

### ISSUE THREAD

**Issue by laozhuang727** [aghoshpub/permutationImportancePhysics#1]
hi,

It is a good tools to do the Permutation Importance, especially for the dnn or more complex model. 

Would you please tell us what kind of model does it support?

**Comment by aghoshpub** [comment]
Hi,

Thanks! And sorry for the late response.

For now it supports Keras, XGBoost, LightGBM. I haven't tested it on many SciKitLearn models yet but they should work. You need to use the `usePredict_poba` keyword to specify whether the model's `predict()` function should be used or `predict_proba()`.

Even a custom model you've defined would work, as long as it has a `predict()` or `predict_proba()` function. This could be made more flexible if required.

I will make it clearer in the next update.

Any model you are interested in particualrly @laozhuang727 ?
